---
- name: Install Apache
  hosts: web
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      tags:
        - apache

    - name: Start Apache
      service:
        name: apache2
        state: started
      tags:
        - apache
